import Head from "next/head";
import HomePage from "../components/HomePage";
import NavBar from "../components/NavBar";
import NavItems from "../components/NavItems";
import TopNavBar from "../components/TopNavBar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Victoria Secret Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopNavBar />
      <NavBar />
      <NavItems />
      <HomePage />
      <div className="my-20"></div>
    </div>
  );
}
