import Head from 'next/head'
import MainNav from './components/MainNav'
import TopNavBar from './components/TopNavBar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Victoria's Secret Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopNavBar />
      <MainNav />
    </div>
  )
}
